# Generated by Django 3.1 on 2020-12-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
