# Generated by Django 3.1 on 2020-12-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz_test', '0002_questions_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='option',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
